### ISSUE TITLE
Feature- Invalidate existing tokens automatically on character transfer

### ISSUE THREAD

**Issue by Aidansavage** [ccpgames/sso-issues#11]
Related to #5 and #6 , would it be possible for SSO to automatically revoke existing authentications? Mainly due to players potentially not knowing what apps that character was previously authorized for, and not knowing, or being able to, revoke those apps themselves.

**Comment by Robbilie** [comment]
#5 is requesting what you want, access_tokens only stay valid for 20 minutes so even though it would be nice to have, not rly necissary with that short timeframe, although i guess when they implement the refresh_token invalidation as requested in the 5 issue theyll prolly also invalidate access_tokens

**Comment by Aidansavage** [comment]
Ideally it would also invalidate any outstanding authentication codes as well, if those persist for any amount of time, as it could be possible to still obtain an (at that point) unauthorized token for that character that would not be invalidated due to only existing after the character was transferred.

**Comment by stebet** [comment]
This has been fixed and deployed.
