### ISSUE TITLE
[Modification] Rename "Cancel" button in character selection form

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/sso-issues#2]
# Feature / Modification Request

### Description
On the character selection form there are two buttons, "Authorize" and "Cancel". The cancel button logs the user out instead of canceling the oauth flow. Renaming it to "Logout" or redirecting back to the referrer (preferred) would be appreciated.

### Use case
Accidentally logging the user out because a "back" button behaviour is expected can be prevented this way.

**Comment by Slivo-fr** [comment]
Renaming the button to logout is a better solution imo, usefull if you got multiples account to work with

**Comment by Robbilie** [comment]
I would prefer it to stay cancel and actually cancel, an additional Logout button somewhere else would help though…

**Comment by Slivo-fr** [comment]
If we can have both, I'm all with you.
If we can't on the other hand, I'd rather have the logout

**Comment by stebet** [comment]
This will work properly as a "Cancel" mechanism when https://github.com/ccpgames/sso-issues/issues/3 is fixed, by logging you out and redirecting back to the original oauth/authorize url, causing you to log-in again (effectively canceling the earlier login) but still continue with the flow.

**Comment by Slivo-fr** [comment]
The label is still confusing imo

**Comment by Robbilie** [comment]
imo too, i would just call it logout because that is what it does, i still feel like cancel should redirect to the referrer

**Comment by Aidansavage** [comment]
Leaving it as cancel makes more sense. You _ARE_ cancelling the authorization request after all. Perhaps an additional button a bit below that says "switch accounts"? If it's possible to retain the initial redirect through the logout/login process at least.

**Comment by Robbilie** [comment]
when you press a button on any website that says CANCEL and logs you out it is also cancelling your session, doesnt mean it makes more sense this way when the button simply logs you out.

**Comment by stebet** [comment]
I'm pretty sure the initial redirect is kept. If not that's definitely a bug. I'll take a closer look. This can be a but confusing since we do not currently have a session per se (just the auth cookie), for performance reasons. Anyways, I'll see what we can do.
