### ISSUE TITLE
Filter scopes on app creation

### ISSUE THREAD

**Issue by bahrmichael** [ccpgames/sso-issues#21]
# Feature / Modification Request

### Description
Search box to filter for scopes to select. Nothing fancy, just a filter. One could enter "orders" and it would reduce the scopes to only those that contain "orders". The browser search doesn't work on the current list (as in can't highlight matches).

Someone already created a script 10 months ago: https://www.reddit.com/r/evetech/comments/6300gy/eve_developers_scope_search_box/

### Use case
Every app creation that needs certain scopes that have to be searched in the list. I would say this is 90% or more of new apps.

---

Please let me know if I can help you with some html/js snippets.

**Comment by BaldvinTh** [comment]
Deployed to developers.testeveonline.com

**Comment by bahrmichael** [comment]
Thanks for the quick update!

> The browser search doesn't work on the current list (as in can't highlight matches).

Have to pull that one back. Apparently it works by now.

**Comment by BaldvinTh** [comment]
Deployed to developers.eveonline.com
