### ISSUE TITLE
Access to structure information is blocked if not on ACL

### ISSUE THREAD

**Issue by AlanLeHun** [ccpgames/sso-issues#23]
# Feature / Modification Request

### Description
At the moment, a 403 is returned from  /universe/structures/{structure_id}/ if the character providing the access token is not on the ACL of the structure requested. The only information returned from this call is the name of the structure and the solar system id. Information which is provided freely in-game.

### Use case
If a user changes corp (yes, I know, I should have checked beforehand) then said user may find that they are no longer on the ACL of structures that they have assets in. In devloping my app, I have come accross this very situation. I can get the the asset from /characters/{character_id}/assets/ but the location_id is effectively useless if I am no longer on the ACL, despite being able to get that information in-game from my assets list.

There should be no need to be on the ACL to get structure information from /universe/structures/{structure_id}/

**Comment by lukasni** [comment]
Not an SSO issue, this should be in esi-issues.

**Comment by ghost** [comment]
Yep, this is def not an SSO request. An explanation for why we made this decision is here: https://github.com/ccpgames/esi-issues/issues/674
