### ISSUE TITLE
Respond to OPTIONS requests at https://login.eveonline.com/oauth/verify

### ISSUE THREAD

**Issue by aldenbe** [ccpgames/sso-issues#27]
# Modification Request

### Description
Currently https://login.eveonline.com/oauth/verify uses a get request with a token in "Authorization" header. This causes a preflight check which fails in browsers. 

### Use case
Web apps currently are unable to get characterID natively. This would solve that.

###Alternate solution
Alternately allowing a post request with authorization in the body instead of as a header would solve this.

**Comment by fuzzysteve** [comment]
https://esi.tech.ccp.is/verify/

has appropriate support :D

**Comment by aldenbe** [comment]
Thank you, in that case might I suggest updating http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/obtaincharacterid.html with that information.

**Comment by aldenbe** [comment]
Resolved
