### ISSUE TITLE
[Bug] Character selection "Cancel" button produces error

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/sso-issues#3]
# Bug

### Reproduction Steps
1. Go to sso page, login and get to the character selection page.
2. Press "Cancel" button
3. See error code.

### Actual Behaviour
Pressing the cancel button triggers a redirect that malforms the url.
Reloads https://login.eveonline.com/oauth/authorize
Redirects to https://login.eveonline.com/account/logoff?returnUrl=https%253a%252f%252flogin.eveonline.com%252foauth%252fauthorize
Redirects to https://login.eveonline.com/account/https%3a%2f%2flogin.eveonline.com%2foauth%2fauthorize
Redirects to https://login.eveonline.com/Error?aspxerrorpath=/account/https:/login.eveonline.com/oauth/authorize

### Expected Behaviour
Not error.

**Comment by Kupuyc** [comment]
I reported this bug 10 Aug via https://community.eveonline.com/support/bug-reports (EBR-125746). More than 45 days . Bug still in state "Open".

**Comment by stebet** [comment]
This has been fixed and deployed
