### ISSUE TITLE
Auth page - character selection UI

### ISSUE THREAD

**Issue by Seavert** [ccpgames/sso-issues#32]
# Feature / Modification Request
### Description
Replace dropdown character menu with radio button.
Default "no character" point can be added to implement/fix #30.
### Use case
List is short enough to be shown, and this will allow to select with 1 click instead of 2 (which is especially nice with buried #10).

**Comment by Aidansavage** [comment]
IMO changing it to the same login style the forums use would be better.

**Comment by ddavaham** [comment]
I am so for the Character Selection UI that the forums use. However, how would the scopes list play into that UI? Would it add an additional page to display the scopes? Would it require the user to scroll down to the review the scopes? Questions that need answers, despite how much we admire the UI that the forums use.

**Comment by Aidansavage** [comment]
push character selection to the top of the screen, followed by scopes, then the confirmation/cancel at the bottom. Scrolling to review scopes is not much of an issue because for some apps (ei auth systems) users already have to scroll.

**Comment by Seavert** [comment]
Exact forum page is overkill. But similar vertical list with small portraits would be nice as well.

**Comment by stebet** [comment]
This is fixed in the v2 OAuth endpoints. The older endpoints will not be migrated to use the new flow as they are on a deprecation path.
