### ISSUE TITLE
Roles through titles not applied

### ISSUE THREAD

**Issue by jbs1** [ccpgames/sso-issues#35]
# Bug
It seems that roles, that are applied through titles don't apply to the api.

### Reproduction Steps
Assign a role, eg.  "Junior Accountant" to a title ingame. Then assign that title to a member.
Ingame the title will appear under the "Role Summary" (https://i.imgur.com/OykimuB.png) the "Roles" tab it will still be crossed out (https://i.imgur.com/MqiD900.png). But ingame the title is needed for works, like i can see corp bills and such things now.

### Actual Behaviour
When using the esi with any endpoint that requires the roles it will throw some "You dont have the roles" error.

### Expected Behaviour
Not throw the error and simply accept the role when it is applied through titles.

**Comment by fuzzysteve** [comment]
Can you give an example of an endpoint it's affecting?

**Comment by jbs1** [comment]
moved to https://github.com/ccpgames/esi-issues/issues/923
