### ISSUE TITLE
SSO error 500

### ISSUE THREAD

**Issue by Grasume** [ccpgames/sso-issues#39]
### Reproduction Steps
Send a post to https://login.eveonline.com/oauth/token as Json and you get
  Internal server error. Error ref: v8zwjFj0xjA=

# Feature / Modification Request

Should return use 'Content-Type': 'application/x-www-form-urlencoded',

**Comment by Aidansavage** [comment]
Using application/json works if you properly arrange the request as noted here at the bottom: https://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/authentication.html    

If it still fails when properly assembled, then this nonstandard function was removed.

**Comment by stebet** [comment]
Posting JSON objects to the OAuth endpoints is not supported (even though it might work). Please adhere to the OAuth RFC and use standard form URL encoding: https://tools.ietf.org/html/rfc6749
