### ISSUE TITLE
Issuer claim is missing https scheme

### ISSUE THREAD

**Issue by a-tal** [ccpgames/sso-issues#41]
# Bug

the `iss` claim in v2 is missing the `https` schema as required by [spec](https://openid.net/specs/openid-connect-discovery-1_0.html) 

```
issuer
REQUIRED. URL using the https scheme with no query or fragment component
that the OP asserts as its Issuer Identifier. If Issuer discovery is 
supported (see Section 2), this value MUST be identical to the issuer value 
returned by WebFinger. This also MUST be identical to the iss Claim value in ID 
Tokens issued from this Issuer.
```

### Actual Behaviour
`"iss":"login.eveonline.com"`

### Expected Behaviour

`"iss":"https://login.eveonline.com"`

**Comment by stebet** [comment]
Yup, saw it's been included in the OAuth Discovery spec as well (see: https://tools.ietf.org/html/rfc8414). Will fix once I'm sure all internal clients can handle this properly as well as most 3rd party devs. To be safe, clients should handle both cases for the time being.

**Comment by a-tal** [comment]
ESI is now prepared for this change

**Comment by mhutter** [comment]
Any timeline for this? Unfortunately this breaks compatibility with most OIDC client libraries...

**Comment by antihax** [comment]
Also running into this issue with a standard oidc library. It would be nice to have it working now V2 is required.

```panic: oidc: issuer did not match the issuer returned by provider, expected "https://login.eveonline.com" got "login.eveonline.com"```

**Comment by iShaymus** [comment]
Hi Team. Any update on this?  

Not having OIDC working is really limiting factor in rolling out easy to deploy boilerplate EVE apps.

**Comment by rms81** [comment]
Hi everybody. Any news on this one?

**Comment by tkhamez** [comment]
If you change this, please do not forget to update the metadata at https://login.eveonline.com/.well-known/oauth-authorization-server.

**Comment by HakShak** [comment]
https://forums.eveonline.com/t/eve-sso-jwt-token-update-on-19-october-11-00-utc/

Better late than never?

**Comment by soratidus999** [comment]
> https://forums.eveonline.com/t/eve-sso-jwt-token-update-on-19-october-11-00-utc/
> 
> Better late than never?

11:25 UTC - 19th October: This change was implemented at 11:00 UTC, however, it has been temporarily reverted to resolve additional underlying issues. This deployment has been postponed for now. I’ll update this post once a new date/time is established.

**Comment by stebet** [comment]
@HakShak You might want to assign the GitHub issue to someone other than me 🤣

**Comment by HakShak** [comment]
I refuse @stebet!

Still technically your work that eventually rolled out for this 🤣 

Also, this was finally done on 2023-10-31

**Comment by stebet** [comment]
> I refuse @stebet!
> 
> 
> 
> Still technically your work that eventually rolled out for this 🤣 
> 
> 
> 
> Also, this was finally done on 2023-10-31

Awesome! Where do I send the contractor work invoice? 😂
