### ISSUE TITLE
[SSOv2] Authorization Failure on verify endpoint

### ISSUE THREAD

**Issue by BitSec01** [ccpgames/sso-issues#52]
# Bug
When making a GET request to https://esi.evetech.net/verify it responds with { "error": "authorization failure" }

**EDIT:** Discovered today that this does not only apply for /verify endpoint but basically every authentication protected enpoint (legacy, latest, dev) I tried them all.

### Reproduction Steps
I've asked on the Slack and on Reddit but I haven't yet found anyone with the same issue.

1. Get a JWT token
2. Send a GET request with "Authorization: Bearer JWT_token" header

### Actual Behaviour
Returns
```json
{ "error": "authorization" }
```

### Expected Behaviour
Returning my character information

**Comment by Kyria** [comment]
I know it's not an answer to your issue, but why don't you extract all data and validate the token yourself if you have the JWT token, instead of using the /verify endpoint ? 

edit to below answers: understood. :)

**Comment by BitSec01** [comment]
@Kyria I am extracting / validating the token myself now. I was just very confused that the /verify endpoint doesn't work for me but does work for others.

**Comment by lukasni** [comment]
I've asked him to make the issue here since it's supposed to be possible to drop-in replace v1 with v2 urls and to have it documented here. It's a really weird behaviour that I wasn't able to replicate and I though we might want to track it somewhere.

**Comment by BitSec01** [comment]
I have no idea how the API is setup. MOST third parties are still using SSOv1 it seems. SSOv1 works perfect for me. I found a /verify endpoint for SSOv2 for anyone interested: https://login.eveonline.com/oauth/verify

I still haven't found a solution to why my JWT token isn't accepted at any endpoint but I'll continue to look at github documentation of SSOv2 auths and third parties that use SSOv2 because it has better documentation and is less confusing.
