### ISSUE TITLE
[Bug] character owner hash not updated on character transfer

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/sso-issues#6]
# Bug

### Reproduction Steps
1. Transfer character to another account

### Actual Behaviour
owner hash staying the same

### Expected Behaviour
character owner hash changes to reflect that the user is not in control of the character anymore

**Comment by frankysaken** [comment]
I'd like to expand on this by saying that not only does the CharacterOwnerHash not change on character transfer (which I think is what it is supposed to be for) but also that the refresh token for the character stays valid and that the grant for that refresh token does not show up under account management.

I don't think we need to get into how big of an issue this is but: bought characters can still have valid refresh tokens for them that are unchangeable and not able to be seen by the new owner and application owners can't tell when characters have changed account to invalidate them from their services.

**Comment by Robbilie** [comment]
just realized i had an issue open for this already ^^
https://github.com/ccpgames/sso-issues/issues/5

**Comment by stebet** [comment]
This will be invalid once tokens are revoked upon on character transfers when https://github.com/ccpgames/sso-issues/issues/11is fixed. Closing this issue.
