### ISSUE TITLE
[Feature] refresh_token invalidation endpoint

### ISSUE THREAD

**Issue by Robbilie** [ccpgames/sso-issues#7]
# Feature / Modification Request

### Description
An endpoint to revoke refresh_tokens (possibly access_tokens as well) like described here: 
https://tools.ietf.org/html/rfc7009

### Use case
Offering the developer the abbility to build in a "logout" functionality and revoke all tokens granted.

**Comment by stebet** [comment]
This is on our roadmap 😊

**Comment by jowrjowr** [comment]
Fantastic!

Please make sure there's an option to do both of the following:

* Kill _ALL_ tokens for this client id & secret tuple

Useful for short term programs that you want to clean up.

* Kill _ALL BUT THIS TOKEN_

Useful for when you request a new set of scopes and don't want a thousand authorizations on the auth page.

**Comment by stebet** [comment]
This is in progress and being implemented according to the RFC spec.

**Comment by stebet** [comment]
We now have this endpoint up and running. You can POST either a access or refresh token to the /oauth/revoke endpoint and it will invalidate the grant associated with that token. We also support the "token_type_hint" parameter so please use that to aid us in determining the token type for faster processing.

Please give the endpoint a go and submit new bugs if you find any issues with it.

**Comment by GoldenGnu** [comment]
It would be really nice if the [SSO documentation](http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/index.html) could be updated with instructions how to use this

**Comment by cvweiss** [comment]
@GoldenGnu I think you just volunteered yourself, you can PR any changes.

**Comment by Robbilie** [comment]
http://eveonline-third-party-documentation.readthedocs.io/en/latest/sso/tokenrevocation.html
