### ISSUE TITLE
"Authorization code is invalid" after switching to V2

### ISSUE THREAD

**Issue by galister** [ccpgames/sso-issues#74]
# Bug

Getting "Authorization code is invalid" after switching to version 2 of the EVE SSO. The implementation I'm using is up to oauth2 spec and have been working fine with V1. The only thing changed was the endpoints being switched to v2.

Note that the refreshing of tokens on the same endpoint works with no issues.

What I know so far:
- It works for some other people/apps. Might be specific to some client IDs?
- The issue is not with the `Authorization` header, as that being incorrect results in a different error
- The issue is not with the `Content-Type` header or the payload's format, because if the SSO fails to read the `grant_type` field, it will return a different error.
- My app adds the `redirect_uri` (as required by oauth2 spec) to the payload. Since this is not included in the EVE SSO docs, so I did not include it in the curl example below. For the record, I did try both with and without.

### Reproduction Steps

Incoming callback after user action at `/v2/oauth/authorize/`.  \
`localhost` is due to the fact that we are behind a loadbalancer.
```

[Tue, 02 Nov 2021 19:15:38 GMT] 
Request starting HTTP/1.0 GET http://localhost:5010/Register?code=Uq5FSujHokeeP9dslBRCjg&state=8c33e397c5814e5f8cf05c3b665a79d

curl -vvv -H "Authorization: Basic [...]" \
-H "Host: login.eveonline.com" \
-H "Content-type: application/x-www-form-urlencoded" \
https://login.eveonline.com/v2/oauth/token \
-d 'grant_type=authorization_code&code=Uq5FSujHokeeP9dslBRCjg'
```

### Actual Behaviour

```
*   Trying 104.18.11.107...
[...]
> POST /v2/oauth/token HTTP/1.1
> Host: login.eveonline.com
> User-Agent: curl/7.52.1
> Accept: */*
> Authorization: Basic [...]
> Content-type: application/x-www-form-urlencoded
> Content-Length: 113

< HTTP/2 400
< date: Tue, 02 Nov 2021 19:16:58 GMT
< content-type: application/json
< cache-control: no-store,no-cache
< pragma: no-cache
< vary: Accept-Encoding
< request-context: appId=cid-v1:2ccf88f2-29b9-460a-bc15-7c0b79926f61
< set-cookie: lang=en; expires=Wed, 02 Nov 2022 19:16:58 GMT; path=/; secure; samesite=lax; httponly
< nel: {"report_to":"default","max_age":31536000,"include_subdomains":true}
< report-to: {"group":"default","max_age":31536000,"endpoints":[{"url":"https://ccpgames.report-uri.com/a/t/g"}],"include_subdomains":true}
< content-security-policy: default-src 'self'; base-uri 'self'; object-src 'self'; img-src 'self' https: data: blob: filesystem:; font-src 'self' web-cdn.eveonline.com fonts.gstatic.com cdnjs.cloudflare.com; style-src 'self' 'unsafe-inline' web-cdn.eveonline.com hello.myfonts.net cdnjs.cloudflare.com; script-src 'self' 'nonce-oHaUPC7hdEeDjLjI5C5dCw==' connect.facebook.net az416426.vo.msecnd.net www.googletagmanager.com www.google-analytics.com static.cloudflareinsights.com 'report-sample' 'strict-dynamic' ; connect-src 'self' dc.services.visualstudio.com www.facebook.com www.google-analytics.com stats.g.doubleclick.net; frame-ancestors launcher.testeveonline.com launcher.eveonline.com; frame-src connect.facebook.net www.facebook.com www.googletagmanager.com; report-uri https://ccpgames.report-uri.com/r/t/csp/enforce
< x-powered-by: ASP.NET
< strict-transport-security: max-age=31536000; includeSubDomains; preload
< cf-cache-status: DYNAMIC
< expect-ct: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
< set-cookie: __cf_bm=TIHvo5ozcrUDKixKJfkvnM0XXF446_QwNCe4WuEloUI-1635880618-0-AQa+BEg4EEli3rbpTJy+kUXLOzm7KX8vCDRMW4iy+lHcj6qwDWGkdG2zNYIvupYbad2gymhNmhD/kAQXYVzbr2Xiauuw5gA6YCH2ik9CL3vV; path=/; expires=Tue, 02-Nov-21 19:46:58 GMT; domain=.eveonline.com; HttpOnly; Secure; SameSite=None
< server: cloudflare
< cf-ray: 6a7fb34879af1cbc-BUD
< alt-svc: h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400
<
* Curl_http_done: called premature == 0
* Connection #0 to host login.eveonline.com left intact
{"error":"invalid_grant","error_description":"Authorization code is invalid."}
```

### Expected Behaviour

A response with an access token and a refresh token.

**Comment by GoldenGnu** [comment]
Double check that you are using `https://login.eveonline.com/v2/oauth/authorize` when sending people to SSO.
You will get character selector with portraits instead of a drop-down with the character names.

**Comment by galister** [comment]
Yes I am using v2 as I wrote in the original post.

**Comment by galister** [comment]
Ok we've discovered that this is based on whose EVE account is doing the logging in. With my EVE account, this happens every time. But I eventually got someone else to help test. They have not been getting this error at all.

**Comment by KotVezdehod** [comment]
I have the same problem. On the first call I get an error 500, and on subsequent calls - 'Authorization code is invalid'.

**Comment by stebet** [comment]
Is this still an issue? Can you reproduce and send me an timestamp for when you did the actual requests and the originating IP addresses so I can take a look in our logs?

**Comment by KotVezdehod** [comment]
> Is this still an issue? Can you reproduce and send me an timestamp for when you did the actual requests and the originating IP addresses so I can take a look in our logs?

No it'snot.
Problem was in my framework (LLC 1C): its standart url-converter skips '+' and '/' symbols. CodeChallenge was initially incorrect.  I fix this situation and now it works fine. 
.net core 5 code works normally too.

Thanks for your response!

**Comment by stebet** [comment]
Alrighty, I'm going to close this ticket then :)
