### ISSUE TITLE
The redirect URL does not match any of the configured values for this client

### ISSUE THREAD

**Issue by Vizis** [ccpgames/sso-issues#78]
How longs it takes to app be registered in a system? Few months ago i've created app but i didnt do anything with it. Today i tried get things to work but can even go throuh 1st step. Link i;'ve created seeps to be ok according to guides. 
https://login.eveonline.com/v2/oauth/authorize/?response_type=code&redirect_uri=http%3A%2F%2Fc------a.pl%2Fcallback&client_id=7--------------------------9&scope=esi-killmails.read_corporation_killmails.v1&state=xyzABC123
I've created new app and tried again but server response is the same "{"error":"invalid_request","error_description":"The redirect URL does not match any of the configured values for this client."}"
```
APPLICATION SETTINGS:
Client ID: 7--------------------9
Secret Key: I---------------------------P
Callback URL: http://c--------------a.pl/callback/
Scopes: COPY SCOPES TO CLIPBOARD
esi-killmails.read_killmails.v1
esi-killmails.read_corporation_killmails.v1
```

**Comment by GoldenGnu** [comment]
> How longs it takes to app be registered in a system

It usually takes about 5 to 10 minutes for any change to take effect (changing scopes, creating a new app, etc.)

**Comment by marchimatteo** [comment]
In the settings the url has a forward slash at the end that is missing on the link.
